# Generated by Django 3.1.5 on 2021-01-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210121_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('menu__name', 'parent__title', 'title')},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
