# Generated by Django 3.1.5 on 2021-01-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20210121_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='url',
            new_name='link',
        ),
    ]
